### ISSUE TITLE
[Bug] Duplicate Rules

### ISSUE THREAD

**Issue by zero77** [salarcode/SmartProxy#270]
**Describe the bug**
I am not sure how it's happened but, i have discovered all of my rules have been duplicated multiple times, i now have 271 rules. Can you prevent SmartProxy from having duplicate rules

**To Reproduce**

**Expected behavior**
To only have one copy of each rule

**Screenshots**

**SmartProxy (please complete the following information):**
 - Version 1.0.7

**Browser (please complete the following information):**
 - Browser Firefox
 - Version 102.8.0

**Additional context**

**Comment by salarcode** [comment]
This should not happen anymore, there as issue in 1.0.5 that is solved now. 
Please reopen this issue if it happens again

**Comment by f1ume** [comment]
I have same problem, using chrome 111 and SmartProxy 1.0.6
today I try to remove some rules, but restrat chrome duplicate rule appear again

**Comment by zero77** [comment]
@salarcode 
I have already updated to 1.0.7

**Comment by clacknya** [comment]
After upgrade to version 1.0.7. I got the same problem in Firefox. When I restart the browser, the rules duplicate. And the problem seem to be solved by uninstall and reinstall the extension.

**Comment by zero77** [comment]
@clacknya 
This didn't work for me it has increased from 271 duplicate rules to 323.

@salarcode 
It looks like this is still happening, do you want me to open another issue.

**Comment by salarcode** [comment]
1.0.8 with a fix for this is released
